version: '3.8'
services:
  golang:
    env_file:
      - ./backend/app/.env
    build:
      context: ./docker
      dockerfile: Dockerfile.backend
    tty: true
    ports:
        - "8080:8080"
    depends_on:
        - db
    volumes:
        - ./backend/app:/go/src/app
    command: sh -c 'go mod tidy && GO_ENV=dev air && GO_ENV=dev go run main.go'
    networks:
        - golang_network
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    restart: always
    networks:
      - golang_network

networks:
    golang_network:
